// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockOrganizer.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MockOrganizer.API.Data.Migrations
{
    [DbContext(typeof(OrganizerDbContext))]
    [Migration("20260910065954_InitialOrganizerTables")]
    partial class InitialOrganizerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MockOrganizer.API.Entities.GateAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gate_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ScanResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scan_result");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<string>("ScannerDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("scanner_device_id");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_code");

                    b.HasKey("Id")
                        .HasName("pk_gate_access_logs");

                    b.HasIndex("TicketCode")
                        .HasDatabaseName("ix_gate_access_logs_ticket_code");

                    b.ToTable("gate_access_logs");
                });

            modelBuilder.Entity("MockOrganizer.API.Entities.MockOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("otp_code");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_email");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_code");

                    b.HasKey("Id")
                        .HasName("pk_mock_otps");

                    b.HasIndex("TicketCode", "OwnerEmail", "IsUsed")
                        .HasDatabaseName("ix_mock_otps_ticket_code_owner_email_is_used");

                    b.ToTable("mock_otps");
                });

            modelBuilder.Entity("MockOrganizer.API.Entities.MockTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("original_price");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_email");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .HasColumnType("text")
                        .HasColumnName("owner_phone");

                    b.Property<string>("SeatZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mock_tickets");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("ix_mock_tickets_ticket_code");

                    b.ToTable("mock_tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
