// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketShield.Infrastructure.Persistence;

#nullable disable

namespace TicketShield.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TicketShieldDbContext))]
    partial class TicketShieldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketShield.Domain.Entities.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisputeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dispute_code");

                    b.Property<Guid>("EscrowId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrow_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_disputes");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_disputes_buyer_id");

                    b.HasIndex("DisputeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_disputes_dispute_code");

                    b.HasIndex("EscrowId")
                        .IsUnique()
                        .HasDatabaseName("ix_disputes_escrow_id");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_disputes_resolved_by");

                    b.ToTable("disputes");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.DisputeEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispute_id");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_dispute_evidences");

                    b.HasIndex("DisputeId")
                        .HasDatabaseName("ix_dispute_evidences_dispute_id");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_dispute_evidences_uploader_id");

                    b.ToTable("dispute_evidences");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.DisputeMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispute_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dispute_messages");

                    b.HasIndex("DisputeId")
                        .HasDatabaseName("ix_dispute_messages_dispute_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_dispute_messages_sender_id");

                    b.ToTable("dispute_messages");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.EscrowTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BuyerFee")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("buyer_fee");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisputeDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispute_deadline");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<decimal>("NetSellerPayout")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("net_seller_payout");

                    b.Property<decimal>("OriginalTicketPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("original_ticket_price");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("payment_reference");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("text")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientIdCard")
                        .HasColumnType("text")
                        .HasColumnName("recipient_id_card");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<decimal>("SellerFee")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("seller_fee");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalBuyerPaid")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_buyer_paid");

                    b.Property<DateTimeOffset?>("UnlockAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlock_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_escrow_transactions");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_escrow_transactions_buyer_id");

                    b.HasIndex("ListingId")
                        .IsUnique()
                        .HasDatabaseName("ix_escrow_transactions_listing_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_escrow_transactions_seller_id");

                    b.ToTable("escrow_transactions");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_end_at");

                    b.Property<DateTimeOffset>("EventStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_start_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTimeOffset>("ResaleDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resale_deadline");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_events_organizer_id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfficialEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("official_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_organizers");

                    b.HasIndex("OfficialEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_organizers_official_email");

                    b.ToTable("organizers");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.PayoutTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("bank_reference_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EscrowId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrow_id");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<string>("PayoutCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payout_code");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RecipientAccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_account_name");

                    b.Property<string>("RecipientAccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_account_number");

                    b.Property<string>("RecipientBankCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_bank_code");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid?>("SellerBankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_bank_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payout_transactions");

                    b.HasIndex("EscrowId")
                        .IsUnique()
                        .HasDatabaseName("ix_payout_transactions_escrow_id");

                    b.HasIndex("PayoutCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payout_transactions_payout_code");

                    b.HasIndex("SellerBankAccountId")
                        .HasDatabaseName("ix_payout_transactions_seller_bank_account_id");

                    b.ToTable("payout_transactions");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.ResaleListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("listing_status");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("original_price");

                    b.Property<string>("OriginalTicketCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_ticket_code");

                    b.Property<string>("PrivateAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("private_access_token");

                    b.Property<decimal>("ResalePrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("resale_price");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_resale_listings");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_resale_listings_event_id");

                    b.HasIndex("OriginalTicketCode")
                        .IsUnique()
                        .HasDatabaseName("ix_resale_listings_original_ticket_code")
                        .HasFilter("listing_status IN ('Verified', 'Transacting')");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_resale_listings_seller_id");

                    b.HasIndex("TierId")
                        .HasDatabaseName("ix_resale_listings_tier_id");

                    b.ToTable("resale_listings");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.TicketTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("original_price");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_tiers");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_ticket_tiers_event_id");

                    b.ToTable("ticket_tiers");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdCardNumber")
                        .HasColumnType("text")
                        .HasColumnName("id_card_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.UserBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_code");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_bank_accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_bank_accounts_user_id");

                    b.ToTable("user_bank_accounts");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Dispute", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.User", "Buyer")
                        .WithMany("Disputes")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_users_buyer_id");

                    b.HasOne("TicketShield.Domain.Entities.EscrowTransaction", "Escrow")
                        .WithOne("Dispute")
                        .HasForeignKey("TicketShield.Domain.Entities.Dispute", "EscrowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_escrow_transactions_escrow_id");

                    b.HasOne("TicketShield.Domain.Entities.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_disputes_users_resolved_by");

                    b.Navigation("Buyer");

                    b.Navigation("Escrow");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.DisputeEvidence", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.Dispute", "Dispute")
                        .WithMany("Evidences")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_evidences_disputes_dispute_id");

                    b.HasOne("TicketShield.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_evidences_users_uploader_id");

                    b.Navigation("Dispute");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.DisputeMessage", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.Dispute", "Dispute")
                        .WithMany("Messages")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_messages_disputes_dispute_id");

                    b.HasOne("TicketShield.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_messages_users_sender_id");

                    b.Navigation("Dispute");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.EscrowTransaction", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.User", "Buyer")
                        .WithMany("PurchasedEscrows")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escrow_transactions_users_buyer_id");

                    b.HasOne("TicketShield.Domain.Entities.ResaleListing", "Listing")
                        .WithOne("EscrowTransaction")
                        .HasForeignKey("TicketShield.Domain.Entities.EscrowTransaction", "ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escrow_transactions_resale_listings_listing_id");

                    b.HasOne("TicketShield.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escrow_transactions_users_seller_id");

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Event", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_organizers_organizer_id");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.PayoutTransaction", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.EscrowTransaction", "Escrow")
                        .WithOne("PayoutTransaction")
                        .HasForeignKey("TicketShield.Domain.Entities.PayoutTransaction", "EscrowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payout_transactions_escrow_transactions_escrow_id");

                    b.HasOne("TicketShield.Domain.Entities.UserBankAccount", "SellerBankAccount")
                        .WithMany("Payouts")
                        .HasForeignKey("SellerBankAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payout_transactions_user_bank_accounts_seller_bank_account_id");

                    b.Navigation("Escrow");

                    b.Navigation("SellerBankAccount");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.ResaleListing", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.Event", "Event")
                        .WithMany("ResaleListings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resale_listings_events_event_id");

                    b.HasOne("TicketShield.Domain.Entities.User", "Seller")
                        .WithMany("ResaleListings")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resale_listings_users_seller_id");

                    b.HasOne("TicketShield.Domain.Entities.TicketTier", "Tier")
                        .WithMany("ResaleListings")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resale_listings_ticket_tiers_tier_id");

                    b.Navigation("Event");

                    b.Navigation("Seller");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.TicketTier", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.Event", "Event")
                        .WithMany("TicketTiers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_tiers_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.UserBankAccount", b =>
                {
                    b.HasOne("TicketShield.Domain.Entities.User", "User")
                        .WithMany("BankAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_bank_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Dispute", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.EscrowTransaction", b =>
                {
                    b.Navigation("Dispute");

                    b.Navigation("PayoutTransaction");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Event", b =>
                {
                    b.Navigation("ResaleListings");

                    b.Navigation("TicketTiers");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.ResaleListing", b =>
                {
                    b.Navigation("EscrowTransaction");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.TicketTier", b =>
                {
                    b.Navigation("ResaleListings");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.User", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Disputes");

                    b.Navigation("PurchasedEscrows");

                    b.Navigation("ResaleListings");
                });

            modelBuilder.Entity("TicketShield.Domain.Entities.UserBankAccount", b =>
                {
                    b.Navigation("Payouts");
                });
#pragma warning restore 612, 618
        }
    }
}
